# This file consist of the downloading the data and stroing in the specific 
# path for fetching dynamically

# sourece Url - we can change by just replacing it with our dataset download link 

artifacts_root: artifacts
# test

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ShreyasDominator/Datasets/raw/refs/heads/main/Census_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Census_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  preprocess_data_path: artifacts/data_preprocessed

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preprocessed/preprocessed_data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
